<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../layout/header.jsp"%>

<style>
.form-control-date {
	width: 100px;
	height: 50px;
}

.pagination {
	justify-content: center;
	margin-top: 50px;
}
</style>

<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css">

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<input class="form-control mb-4" placeholder="어디로 여행가시나요?">
		</div>
		<div class="col-md-6 d-flex justify-content-end">
			<button class="btn btn-primary mb-4 me-2" id="dateButton"
				type="button">조회기간</button>
			<div class="input-daterange input-group" id="datepicker"
				style="display: none;">
				<input type="text" class="form-control form-control-date"
					name="start" placeholder="시작 날짜를 선택하세요" style="width: 140px;" />
				<div class="input-group-addon">to</div>
				<input type="text" class="form-control form-control-date" name="end"
					placeholder="종료 날짜를 선택하세요" style="width: 140px;" />
			</div>
			<button class="btn btn-primary mb-4" type="submit">지역별 검색</button>
		</div>
	</div>

	<!-- Here is the newly added div for location list -->
	<div id="location-list-div" style="display:none">
		<ol class="list-group list-group-numbered" id="location-list">
		  <!-- The list will be generated by JavaScript -->
		</ol>
	</div>

	<div class="row row-cols-1 row-cols-md-3 g-4">
		<%
			for (int i = 0; i < 16; i++) {
		%>
		<div class="col">
			<div class="card h-100">
				<div id="map<%=i%>" style="height: 200px;"></div>
				<div class="card-body">
					<h5 class="card-title">한국 여행 갑시다~</h5>
					<p class="card-text">대한민국 아무데나 여행합시다 ㅎㅎ</p>
					<a class="btn btn-primary" href="#" role="button">일정 상세보기</a>
				</div>
				<div class="card-footer">
					<small class="text-muted">3분전에 작성했습니다</small>
				</div>
			</div>
		</div>
		<%
			}
		%>
	</div>

	<nav aria-label="...">
		<ul class="pagination">
			<li class="page-item disabled"><a class="page-link">Previous</a>
			</li>
			<li class="page-item active" aria-current="page"><a
				class="page-link" href="#">1</a></li>
			<li class="page-item"><a class="page-link" href="#">2</a></li>
			<li class="page-item"><a class="page-link" href="#">3</a></li>
			<li class="page-item"><a class="page-link" href="#">Next</a></li>
		</ul>
	</nav>
</div>



<%@ include file="../layout/footer.jsp"%>
