<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../layout/header.jsp"%>

<style>
.form-control-date {
	width: 100px;
	height: 50px;
}

.pagination {
	justify-content: center;
	margin-top: 50px;
}
</style>

<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css">

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<input class="form-control mb-4" placeholder="어디로 여행가시나요?">
		</div>
		<div class="col-md-6 d-flex justify-content-end">
			<button class="btn btn-primary mb-4 me-2" id="dateButton"
				type="button">조회기간</button>
			<div class="input-daterange input-group" id="datepicker"
				style="display: none;">
				<input type="text" class="form-control form-control-date"
					name="start" placeholder="시작 날짜를 선택하세요" style="width: 140px;" />
				<div class="input-group-addon">to</div>
				<input type="text" class="form-control form-control-date" name="end"
					placeholder="종료 날짜를 선택하세요" style="width: 140px;" />
			</div>
			<button class="btn btn-primary mb-4" type="submit">지역별 검색</button>
		</div>
	</div>

	<!-- Here is the newly added div for location list -->
	<div id="location-list-div" style="display:none">
		<ol class="list-group list-group-numbered" id="location-list">
		  <!-- The list will be generated by JavaScript -->
		</ol>
	</div>

	<div class="row row-cols-1 row-cols-md-3 g-4">
		<%
			for (int i = 0; i < 16; i++) {
		%>
		<div class="col">
			<div class="card h-100">
				<div id="map<%=i%>" style="height: 200px;"></div>
				<div class="card-body">
					<h5 class="card-title">한국 여행 갑시다~</h5>
					<p class="card-text">대한민국 아무데나 여행합시다 ㅎㅎ</p>
					<a class="btn btn-primary" href="#" role="button">일정 상세보기</a>
				</div>
				<div class="card-footer">
					<small class="text-muted">3분전에 작성했습니다</small>
				</div>
			</div>
		</div>
		<%
			}
		%>
	</div>

	<nav aria-label="...">
		<ul class="pagination">
			<li class="page-item disabled"><a class="page-link">Previous</a>
			</li>
			<li class="page-item active" aria-current="page"><a
				class="page-link" href="#">1</a></li>
			<li class="page-item"><a class="page-link" href="#">2</a></li>
			<li class="page-item"><a class="page-link" href="#">3</a></li>
			<li class="page-item"><a class="page-link" href="#">Next</a></li>
		</ul>
	</nav>
</div>

<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAbBV-mR71MB1Oc8kwqjn0bcIG7BEFDGuE&callback=initMap&v=weekly"
	defer></script>

<script>
	function initMap() {
		for (let i = 0; i < 16; i++) {
			let map = new google.maps.Map(document.getElementById("map" + i), {
				zoom : 5,
				center : {
					lat : 37,
					lng : 128
				},
				mapTypeControl : false,
			});
		}
	}
</script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

<script>
	$(document).ready(
			function() {
				var dateRangeInput = $('.input-daterange');

				dateRangeInput.datepicker({
					format : 'yyyy-mm-dd',
					startDate : '0d',
					endDate : '+1y',
					autoclose : true,
				});

				$('#dateButton').click(function(e) {
					e.preventDefault();
					dateRangeInput.show();
					$(this).hide();
				});

				dateRangeInput.on('changeDate', function() {
					if ($('input[name="end"]').val()) {
						$('#dateButton').text(
								$('input[name="start"]').val() + ' - '
										+ $('input[name="end"]').val());
						dateRangeInput.hide();
						$('#dateButton').show();
					}
				});
			});
</script>

<!-- Here is the newly added script for location list -->
<script>
	$(document).ready(function() {
		var locationList = ["서울", "부산", "인천", "대구", "광주", "대전", "울산", "세종", "경기", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주"];
		var locationButton = $('.btn-primary[type="submit"]');
		
		locationButton.click(function(e) {
			e.preventDefault();
			$('#location-list-div').show();
			$('.container *').prop('disabled', true);
			locationList.forEach(function(location) {
				$('#location-list').append('<li class="list-group-item">' + location + '</li>');
			});
			$('#location-list .list-group-item').click(function() {
				locationButton.text($(this).text());
				$('#location-list-div').hide();
				$('#location-list').empty();
				$('.container *').prop('disabled', false);
			});
		});
	});
</script>

<%@ include file="../layout/footer.jsp"%>
