<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
								<%-- 저장된 헤더를 추가합니다 --%>
								<%@ include file="/WEB-INF/view/layout/header.jsp"%>



<style>
.form-control-date {
	width: 100px;
	height: 50px;
}

.pagination {
	justify-content: center;
	margin-top: 50px;
}
</style>

<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css">

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="input-group mb-3">
				<input id=searchInput type="text" class="form-control" placeholder="검색어를 입력하세요" aria-label="Recipient's username" aria-describedby="button-addon2">
				<button class="btn btn-outline-secondary" type="button" id="button-addon2">검색</button>
			  </div>
			  

		</div>
		<div class="col-md-6 d-flex justify-content-end">
			<button class="btn btn-primary mb-4 me-2" id="dateButton"
				type="button">조회기간</button>
			<div class="input-daterange input-group" id="datepicker"
				style="display: none;">
				<input type="text" class="form-control form-control-date"
					name="start" placeholder="시작 날짜를 선택하세요" style="width: 140px;" />
				<div class="input-group-addon">to</div>
				<input type="text" class="form-control form-control-date" name="end"
					placeholder="종료 날짜를 선택하세요" style="width: 140px;" />
			</div>
			<button class="btn btn-primary mb-4" type="submit">지역별 검색</button>
		</div>
	</div>
	<!-- Here is the newly added div for location list -->
	<div id="location-list-div" style="display:none">
		<ol class="list-group list-group-numbered" id="location-list">
		  <!-- The list will be generated by JavaScript -->
		</ol>
	</div>

	

								<%-- 일정게시판의 동적 페이지 넘기기 DB 기능입니다 --%>
									<%@ page import="java.sql.*"%>
									<%@ page import="dbutil.DBUtil"%>
									
									<%
									String pageStr = request.getParameter("page");
									int currentPage = (pageStr == null || pageStr.equals("")) ? 1 : Integer.parseInt(pageStr);
									%>
									
									<%
										Connection conn = DBUtil.getConnection();
									Statement st = null;
									ResultSet rs = null;
									
								int recordsPerPage = 9;
								int offset = (currentPage - 1) * recordsPerPage;
								String sql = "SELECT * FROM scheduleboard LIMIT " + recordsPerPage + " OFFSET " + offset;
									st = conn.createStatement();
									rs = st.executeQuery(sql);
								
								int totalRecords = 0;
								Statement countSt = conn.createStatement();
								try {
								    String countSql = "SELECT COUNT(*) FROM scheduleboard";
								    ResultSet countRs = countSt.executeQuery(countSql);
								    if (countRs.next()) {
								        totalRecords = countRs.getInt(1);
								    }
								    countRs.close();
								} catch (Exception e) {
								    e.printStackTrace();
								}
								countSt.close();
									%>
	
					
								<%-- 일정게시판의 카드 틀입니다 --%>
								<div class="row row-cols-1 row-cols-md-3 g-4">
										<%
											while (rs.next()) {
										%>
										<div class="col">
											<div class="card h-100">
												<iframe id="mapView" frameborder="0"
													style="border: 0; width: 100%; height: 100%;"
													src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAbBV-mR71MB1Oc8kwqjn0bcIG7BEFDGuE&q=<%=rs.getString("location")%>&center=<%=rs.getDouble("wido")%>,<%=rs.getDouble("gyeongdo")%>"
													allowfullscreen> </iframe>
								
												<div class="card-body">
													<h5 class="card-title"><%=rs.getString("location")%></h5>
													<p class="card-text"><%=rs.getString("memo")%></p>
													<p class="card-text">
														<small class="text-muted"></small>
													</p>
													<a href="#" class="btn btn-primary">일정 상세보기</a>
								
												</div>
												<div class="card-footer">
													<small class="text-body-secondary"><%=rs.getString("startwhen")%>부터 <%=rs.getString("endwhen")%>까지</small>
												</div>
											</div>
										</div>
										<%
											}
										%>
								</div>

									<%
										DBUtil.close(conn);
									DBUtil.close(rs);
									DBUtil.close(st);
									%>
									
									
									
									
									
							<%-- 일정게시판의 동적 페이지 넘기기 기능입니다 --%>
									<nav aria-label="...">
									    <ul class="pagination">
									        <li class="page-item <%= currentPage == 1 ? "disabled" : "" %>">
									            <a class="page-link" href="<%= currentPage == 1 ? "#" : "?page=" + (currentPage - 1) %>">Previous</a>
									        </li>
									        <% 
									        for(int i = 1; i <= (totalRecords + recordsPerPage - 1) / recordsPerPage; i++) {
									            if(i == currentPage) {
									        %>
									                <li class="page-item active" aria-current="page">
									                    <a class="page-link" href="#"><%= i %></a>
									                </li>
									        <% 
									            } else {
									        %>
									                <li class="page-item">
									                    <a class="page-link" href="?page=<%= i %>"><%= i %></a>
									                </li>
									        <% 
									            }
									        } 
									        %>
									        <li class="page-item <%= currentPage == (totalRecords + recordsPerPage - 1) / recordsPerPage ? "disabled" : "" %>">
									            <a class="page-link" href="<%= currentPage == (totalRecords + recordsPerPage - 1) / recordsPerPage ? "#" : "?page=" + (currentPage + 1) %>">Next</a>
									        </li>
									    </ul>
									</nav>
</div>

							<%-- 저장된 푸터를 추가합니다 --%>
								<%@ include file="/WEB-INF/view/layout/footer.jsp"%>
							<%-- 저장된 "schedule.js"을 불러옵니다 --%>
								<script src="schedule.js"></script>


							<%-- 일정게시판의 각각의 카드에 구글맵을 띄우는 기능입니다 --%>
									<script>
										function initAllMaps() {
							
											var maps = document.querySelectorAll('[id^="map"]');
							
											maps.forEach(function(mapElement) {
							
												const lat = parseFloat(mapElement.dataset.lat);
												const lng = parseFloat(mapElement.dataset.lng);
												const mapDivId = mapElement.id;
							
												console.log("lat : " + typeof lat);
												console.log(typeof 37);
												console.log(lng);
							
												const centerTest = {
													lat : parseFloat(mapElement.dataset.lat),
													lng : parseFloat(mapElement.dataset.lng)
												};
							
												const map = new google.maps.Map(document
														.getElementById(mapDivId), {
													zoom : 10,
													center : {
														"lat" : lat,
														"lng" : lng
													}
												});
							
												const marker = new google.maps.Marker({
													position : {
														lat : lat,
														lng : lng
													},
													map : map
												});
							
											})
							
										};
									</script>

		<!-- <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAbBV-mR71MB1Oc8kwqjn0bcIG7BEFDGuE&callback=initAllMaps"></script> -->